### ISSUE TITLE
How to validate the same password for password and confirmation fields?

### ISSUE THREAD

**Issue by wpoosanguansit** [jkuatdsc/form-builder#67]
Hi,

Can you you show how to validate the password and confirmation fields? I do have
```
private var passwordConfirmation = mutableStateOf("")


Validators.Custom("Password given must be the same") { password ->
                        password.toString() == passwordConfirmation.value
                    }

And I do have the above in the password TextField and I am trying to capture the confirmation in

TextFieldState(
                name = "password_confirmation",
                validators = listOf(Validators.Required(),
                    Validators.Min(8, "Password must be 8 to 16 characters"),
                    Validators.Max(16,"Password must be 8 to 16 characters"),
                    Validators.Custom("Password given must be the same") { confirmation ->
                        passwordConfirmation.value = confirmation.toString()
                        true
                    }
                )
            )
```

But this does not work. Thanks for your help.

**Comment by joykangangi** [comment]
Hello @wpoosanguansit 👋 ,
I assume you have 2 textfields, one for the Password and another for ConfirmPassword, and each is passed as a `field` in your `FormState` instance. In the [FormBuilder Library](https://github.com/jkuatdsc/form-builder) any input field state such as the [TextFieldState](https://github.com/jkuatdsc/form-builder/blob/main/form-builder/src/main/java/com/dsc/form_builder/TextFieldState.kt) has a property `value` which enables you to access the value of a given input field. Therefore, one does not need to create another variable to store value of an input field.

Building up on this, for your case you can create the custom function that accesses the value in the 'password' TextFieldState and compares it to the value in 'confirm_password' TextFieldState . We don't need to add true when checking otherwise the result will always be true despite the conditions not matching. Note this has to be away from the instatiation of the `formstate` to avoid compilation errors. The code looks like this:
```
val formState: FormState<BaseState<*>> = FormState(
        fields = listOf(
            TextFieldState(
                name = "password",
                validators = listOf(
                    Validators.Min(8, "Password must be 8 to 16 characters"),
                    Validators.Max(16, "Password must be 8 to 16 characters"),
                    Validators.Required(),
                ),
            ),
            TextFieldState(
                name = "confirm_password",
                validators = listOf(
                    Validators.Custom("Password given must be the same") { confirmation ->
                        passwordMatch(confirmation.toString())
                    },
                    Validators.Required(),
                ),
            ))
)

private fun passwordMatch(confirmationPass:String): Boolean {
        return confirmationPass == formState.fields.find { it.name == "password"}?.value.toString()
 }
```
Also, the order of the validators matters, for better UX, consider passing the `Validators.Required()` as the last validator.
